-- Create Expenses Table
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_name text not null,
  expense_date date not null,
  category text not null, -- 'Listrik', 'Air', 'Kebersihan', 'Maintenance', 'Lainnya'
  amount numeric not null default 0,
  description text,
  proof_url text
);

-- Enable RLS
alter table expenses enable row level security;

-- Policy: Allow read/write for all (or restrict as needed)
create policy "Enable all for public" on expenses for all using (true) with check (true);
